### ISSUE TITLE
Provide Demo

### ISSUE THREAD

**Issue by armand1m** [guilhermelimak/react-codejar#1]
Could we have a deployment of the example published in ghpages?

**Comment by antonmedv** [comment]
https://medv.io/codejar/

**Comment by armand1m** [comment]
@antonmedv I know that url, I mean a demo deployment of this package in specific for test purposes 🙂

**Comment by eddingston** [comment]
Are there any examples of react-codejar that uses PrismJS for highlighting? They would be greatly appreciated. Thanks!

**Comment by eddingston** [comment]
Currently I am trying to use it with the HookExample but it doesn't seem to be working. 
```
  const HookExample = () => {
    const [code, setCode] = useState('(format t "lisp example")');

    const editorRef = useCodeJar({
      code, // Initial code value
      onUpdate: setCode, // Update the text
      highlight: PrismJS.highlightElement // Highlight function, receive the editor

    });

    return <div ref={editorRef} className="lang-go"
          code={children.trim()} // Initial code value
          onUpdate={setCode} // Update the text
          highlight={PrismJS.highlightElement} // Highlight function, receive the editor
          style={editorStyles.editor}
        />
```

**Comment by guilhermelimak** [comment]
There's a bug where the editor is rerendering everytime the text changes so it changes the cursor position, still wasn't able to fix that. I'll add that to the readme so people don't think it's working.

The highlight should be working tho. This is what I had on the example:
```js
  const [code, onUpdate] = React.useState(exampleCode);

  const highlight = editor => {
    const text = editor.textContent;

    editor.innerHTML = Prism.highlight(
      text,
      Prism.languages.javascript,
      "javascript"
    );
  };

  const editorRef = useCodeJar({
    code,
    onUpdate,
    highlight
  });

  return (
    <div>
      <h5>Using hooks: </h5>
      <div ref={editorRef}></div>

      <h5>Using component:</h5>
      <ReactCodeJar code={code} onUpdate={onUpdate} highlight={highlight} />
    </div>
  );
```

Can you try it and see if that works? but still, even if the highlight works the re-render bug will prevent you from using this unfortunately. I'll take some time today to think about a fix, but I couldn't figure it out before.

**Comment by eddingston** [comment]
I appreciate your quick response. 

```
  import React, { useEffect, useState, useRef } from 'react';
  import PrismJS from 'prismjs';
  import { ReactCodeJar, useCodeJar } from "react-codejar";

  const HookExample = () => {
    const [code, onUpdate] = useState(`var x = "helloworld"`);

    const highlight = editor => {
      const text = editor.textContent;
  
      editor.innerHTML = PrismJS.highlight(
        text,
        PrismJS.languages.javascript,
        "javascript"
      );
    };
  
    const editorRef = useCodeJar({
      code,
      onUpdate,
      highlight
    });
  
    return (
      <div>
        <div ref={editorRef}></div>
      </div>
    );
  };
```
I'm using the code above and it is still not highlighting. This is currently within Docusaurus2, would that be a problem? Thanks.

**Comment by guilhermelimak** [comment]
A very crude demo can now be found [here](https://guilhermelimak.github.io/react-codejar/).

@eddingston Sorry for the delayed response, don't know if you solved it already but I updated the lib with a fix for the previous issue I mentioned. If you are still having issues can you create a new issue and post a codesandbox link for repro so I can take a look?

**Comment by peakercope** [comment]
Hey guys I think you forgot import styles
```javascript
import 'prismjs/themes/prism.css';
```
